import { DM_Sans, Inter } from "next/font/google";
import "./globals.css";
import TransitionProvider from "@/components/transitionProvider";

// const inter = Inter({ subsets: ["latin"] });
const font = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Lama Dev Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className="w-screen h-screen bg-gradient-to-b from-blue-100 to-red-100">
          <div className="h-screen">
            <TransitionProvider>{children}</TransitionProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
